#!/usr/bin/env node
// Writes src/css.generated.ts: `figureCss` (src/figure.css verbatim) and
// `chartTokensCss` (the --chart-* tokens resolved to literal values per theme,
// read from @tangle-network/brand tokens.css).
//
//   node scripts/gen-css.mjs           write the file
//   node scripts/gen-css.mjs --check   exit 1 when the file is stale
//
// A standalone document (a PDF report, a sandboxed iframe) has no brand
// stylesheet, so it embeds `chartTokensCss`: light on :root, dark under
// prefers-color-scheme and [data-theme="dark"], and light again for print.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(here, '..')
const TOKENS = path.join(root, '..', 'brand', 'src', 'styles', 'tokens.css')
const FIGURE = path.join(root, 'src', 'figure.css')
const OUT = path.join(root, 'src', 'css.generated.ts')

const css = fs.readFileSync(TOKENS, 'utf8').replace(/\/\*[\s\S]*?\*\//g, '')
const blocks = [...css.matchAll(/([^{}]+)\{([^{}]*)\}/g)].map(([, sel, body]) => ({
  selectors: sel.split(',').map((s) => s.trim()),
  colorScheme: body.match(/(?:^|;)\s*color-scheme\s*:\s*(light|dark)\s*;/)?.[1],
  decls: new Map([...body.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/g)].map(([, k, v]) => [k, v.trim()])),
}))
const find = (label, test) => {
  const block = blocks.find(test)
  if (!block) throw new Error(`gen-css: no ${label} block in ${TOKENS}`)
  return block.decls
}
const darkSpine = find('dark spine', (b) => b.selectors.includes('.dark') && b.colorScheme === 'dark' && b.decls.has('--text-primary'))
const lightSpine = find('light spine', (b) => b.selectors.includes('.light') && b.colorScheme === 'light' && b.decls.has('--text-primary'))
const chartBase = find('chart', (b) => b.decls.has('--chart-ink'))
const chartLight = find('light chart', (b) => b.selectors.includes('.light') && b.decls.has('--chart-accent') && !b.decls.has('--chart-ink'))

function resolve(value, env, depth = 0) {
  if (depth > 10) throw new Error(`gen-css: var() cycle at ${value}`)
  return value.replace(/var\((--[a-z0-9-]+)\)/g, (_, name) => {
    const v = env.get(name)
    if (v === undefined) throw new Error(`gen-css: ${name} is not defined`)
    return resolve(v, env, depth + 1)
  })
}

function theme(spine, chart, canvas) {
  const env = new Map([...darkSpine, ...spine, ...chart])
  const out = [...chart.keys()].filter((k) => k.startsWith('--chart-')).map((k) => `${k}:${resolve(chart.get(k), env)}`)
  out.push(`--chart-canvas:${resolve(canvas, env)}`)
  return out.join(';')
}

const dark = theme(darkSpine, chartBase, 'var(--depth-1)')
const light = theme(lightSpine, new Map([...chartBase, ...chartLight]), 'var(--md3-surface-container-lowest)')
const tokensCss = [
  `:root{${light};color-scheme:light}`,
  `@media (prefers-color-scheme: dark){:root:not([data-theme="light"]){${dark};color-scheme:dark}}`,
  `:root[data-theme="dark"]{${dark};color-scheme:dark}`,
  `@media print{:root,:root:not([data-theme="light"]),:root[data-theme="dark"]{${light};color-scheme:light}}`,
].join('\n')

const figureCss = fs.readFileSync(FIGURE, 'utf8')
const file = `// Generated by scripts/gen-css.mjs from src/figure.css and @tangle-network/brand tokens.css. Do not edit.

/** The figure block and mark styles (src/figure.css), for documents that inline their CSS. */
export const figureCss: string = ${JSON.stringify(figureCss)};

/** --chart-* resolved per theme, for documents without brand tokens: light, dark by preference or [data-theme="dark"], light in print. */
export const chartTokensCss: string = ${JSON.stringify(tokensCss)};
`

if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
  if (current !== file) {
    console.error('src/css.generated.ts is stale: run `pnpm --filter @tangle-network/charts gen:css`')
    process.exit(1)
  }
} else {
  fs.writeFileSync(OUT, file)
  console.log(`wrote ${path.relative(root, OUT)}`)
}
