packages:
  - "packages/*"

overrides:
  browserslist: 4.28.7
  electron-to-chromium: 1.5.418
  "@rolldown/binding-wasm32-wasi>@napi-rs/wasm-runtime": 1.1.6
  "@oxc-parser/binding-wasm32-wasi>@napi-rs/wasm-runtime": 1.1.6
  "@oxc-resolver/binding-wasm32-wasi>@napi-rs/wasm-runtime": 1.1.6
  "@tiptap/core": ">=3.30.4 <4.0.0"
  "@tiptap/pm": ">=3.30.4 <4.0.0"
  "@babel/core": ">=7.29.6 <8.0.0"
  esbuild: ">=0.28.1 <0.29.0"

allowBuilds:
  canvas: false
  esbuild: true
