import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import postcss from "postcss";

const styles = new URL("../src/styles/", import.meta.url);

/** Project canonical CSS, changing only the unpinned root's default mode.
 * No palette, token-name allowlist, CSS variable resolver or theme DSL lives
 * here. Explicit selectors keep their specificity and their original values.
 */
export function generateCompatibility(tokens, namedThemes) {
  const css = postcss.parse(`${tokens}\n${namedThemes}`);
  let hasRoot = false;
  let hasLight = false;
  css.walkRules((rule) => {
    const selectors = rule.selectors;
    hasRoot ||= selectors.includes(":root");
    hasLight ||= selectors.includes(".light");
    // Zero-specificity defaults cannot beat .dark/[data-theme] on <html>.
    // Add the same root to light overrides, later in the canonical cascade.
    rule.selectors = [...new Set([
      ...selectors.map((selector) => selector === ":root" ? ":where(:root)" : selector),
      ...(selectors.includes(".light") ? [":where(:root)"] : []),
    ])];
  });
  if (!hasRoot || !hasLight) throw new Error("Canonical root/light mode rules are missing");
  // Agent App deliberately leaves --radius owned by its host (often in a
  // Tailwind layer). The compatibility sheet must not seize that public knob.
  css.walkDecls("--radius", (decl) => decl.remove());
  css.walkComments((comment) => comment.remove());
  // Stable, readable output, independent of source comments/whitespace.
  css.walk((node) => { node.raws = { semicolon: true }; });
  const digest = createHash("sha256").update(tokens).update("\n").update(namedThemes).digest("hex");
  return `/* GENERATED by scripts/gen-compat.mjs. Do not edit.\n * Source: tokens.css + named-themes.css\n * SHA-256: ${digest}\n * Light-default compatibility; all explicit modes remain canonical.\n */\n${css.toString().trimEnd()}\n`;
}

export function checkCompatibility(expected, actual) {
  if (expected !== actual) {
    throw new Error("Stale legacy-light.css; run pnpm --filter @tangle-network/brand gen:compat");
  }
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  const args = process.argv.slice(2);
  if (args.some((arg) => arg !== "--check")) throw new Error("Usage: gen-compat.mjs [--check]");
  const output = new URL("legacy-light.css", styles);
  const generated = generateCompatibility(
    readFileSync(new URL("tokens.css", styles), "utf8"),
    readFileSync(new URL("named-themes.css", styles), "utf8"),
  );
  if (args.includes("--check")) {
    checkCompatibility(generated, readFileSync(output, "utf8"));
    console.log("Canonical light-default compatibility stylesheet is current.");
  } else {
    writeFileSync(output, generated);
    console.log(`Generated ${fileURLToPath(output)}`);
  }
}
