#!/usr/bin/env node
// Writes ladders.css and system.css from radix-ramps.json.
//
//   node scripts/gen-ladders.mjs [--check] [ramps.json] [out-dir]
//
// out-dir must hold the tokens.css whose tone regions are rewritten.
//
// It also writes the categorical tone family into the two marked regions of
// tokens.css (plus their data-tone scopes) and the agents named theme into
// named-themes.css, so every consumer of the canonical stylesheet (and the
// legacy-light projection generated from it) carries the same values. --check
// writes nothing and fails when any of the four outputs is stale.
//
// radix-ramps.json holds the @radix-ui/colors 3.0.0 values as static data, so
// the generated CSS has no runtime dependency. Apps that ship ahead of a brand
// release copy the two generated files verbatim; running this script is the
// only way to change a value, so every copy stays identical.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const args = process.argv.slice(2)
const CHECK = args.includes('--check')
const [rampsArg, outArg] = args.filter((a) => a !== '--check')
const RAMPS_FILE = rampsArg ?? path.join(here, 'radix-ramps.json')
const OUT = outArg ?? path.join(here, '..', 'src', 'styles')
const R = JSON.parse(fs.readFileSync(RAMPS_FILE, 'utf8'))

const RAMPS = [
  'mauve', 'iris', 'green', 'amber', 'red', 'blue', 'plum', 'orange', 'grass', 'bronze', 'crimson', 'olive',
  'purple', 'teal', 'pink', 'brown', 'cyan', 'lime',
]
const ROLE = { gray: 'mauve', accent: 'iris', success: 'green', warning: 'amber', danger: 'red', info: 'blue' }
const DOMAIN = {
  personal: 'plum',
  hospitality: 'orange',
  tax: 'grass',
  law: 'blue',
  procurement: 'bronze',
  negotiation: 'crimson',
  logistics: 'amber',
  defense: 'olive',
}
for (const r of RAMPS) {
  for (const t of ['light', 'dark']) {
    if (!Array.isArray(R[r]?.[t]) || R[r][t].length !== 12) throw new Error(`${r} ${t}: expected 12 steps`)
  }
}

const DARK_SEL = ':root,\n[data-sandbox-ui],\n[data-theme="dark"],\n.dark'
const LIGHT_SEL = '[data-sandbox-theme="vault"],\n[data-theme="light"],\n.light'

// ── ladders.css ────────────────────────────────────────────────────────────
const steps = (theme) =>
  RAMPS.map((r) => R[r][theme].map((v, i) => `  --${r}-${i + 1}: ${v};`).join('\n')).join('\n')
const roles = Object.entries(ROLE)
  .map(([role, ramp]) => Array.from({ length: 12 }, (_, i) => `  --${role}-${i + 1}: var(--${ramp}-${i + 1});`).join('\n'))
  .join('\n')
const domainBlock = (sel, ramp) =>
  `${sel} {\n${Array.from({ length: 12 }, (_, i) => `  --domain-${i + 1}: var(--${ramp}-${i + 1});`).join('\n')}\n  --domain-bubble: ${R[ramp].light[10]};\n}`

const ladders = `/* Colour ladders. Generated by scripts/gen-ladders.mjs from @radix-ui/colors 3.0.0; do not edit by hand.
 *
 * Every ramp has 12 steps, and each step has one job:
 *   1-2   app backgrounds
 *   3-5   control fills: rest, hover, pressed
 *   6-8   borders: subtle, default, hover
 *   9-10  solid fills
 *   11    readable secondary text
 *   12    readable primary text
 * Light and dark use the same names, so a component written against a step
 * works in both themes. Dark is the :root default and light wins by source
 * order, the same as tokens.css. The role aliases repeat in both blocks because
 * a var() resolves where it is declared. */
${DARK_SEL} {
${steps('dark')}
${roles}
}
${LIGHT_SEL} {
${steps('light')}
${roles}
}

/* Domain ramp. Set data-domain on a cover, tile, avatar or listing and read
 * --domain-1..12. An unknown domain gets the brand ramp. --domain-bubble is the
 * light step 11 in both themes: white text on it passes 4.5:1 for every domain.
 * A step 9 fill never carries text (white on orange 9 is 2.97:1). */
${domainBlock(':root,\n[data-domain]', 'iris')}
${Object.entries(DOMAIN).map(([d, r]) => domainBlock(`[data-domain="${d}"]`, r)).join('\n')}
`

// ── system.css ─────────────────────────────────────────────────────────────
const hex = (ref, theme) => {
  if (ref.startsWith('#')) return ref
  const [ramp, step] = ref.split('-')
  return R[ramp][theme][Number(step) - 1]
}
const hsl = (h) => {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16) / 255)
  const max = Math.max(r, g, b)
  const min = Math.min(r, g, b)
  const l = (max + min) / 2
  let s = 0
  let hue = 0
  if (max !== min) {
    const d = max - min
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
    hue = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4
    hue *= 60
  }
  return `${Math.round(hue)} ${Math.round(s * 1000) / 10}% ${Math.round(l * 1000) / 10}%`
}

const W = '#ffffff'
// [token, light, dark, kind]. kind 'hsl' emits an "H S% L%" triplet for the
// shadcn layer; otherwise the value is var(--ramp-n) or a literal.
const MAP = [
  // Product semantic tokens.
  ['bg-page', W, 'mauve-1'],
  ['bg-subtle', 'mauve-2', 'mauve-2'],
  ['bg-card', W, 'mauve-2'],
  ['bg-raised', W, 'mauve-3'],
  ['bg-control', 'mauve-3', 'mauve-3'],
  ['bg-control-hover', 'mauve-4', 'mauve-4'],
  ['bg-control-active', 'mauve-5', 'mauve-5'],
  ['line-subtle', 'mauve-6', 'mauve-6'],
  ['line', 'mauve-7', 'mauve-7'],
  ['line-strong', 'mauve-8', 'mauve-8'],
  // Input borders: 3.30:1 on white and 3.45:1 on dark step 2, above the 3:1 floor for controls.
  ['line-field', 'mauve-9', 'mauve-9'],
  ['fg', 'mauve-12', 'mauve-12'],
  ['fg-muted', 'mauve-11', 'mauve-11'],
  // Icons and disabled states only; 3.77:1 is below the body-text floor.
  ['fg-faint', 'mauve-10', 'mauve-10'],
  ['ink', 'mauve-12', 'mauve-12'],
  ['on-ink', W, 'mauve-1'],
  ['accent-solid', 'iris-9', 'iris-9'],
  ['accent-solid-hover', 'iris-10', 'iris-10'],
  ['accent-text', 'iris-11', 'iris-11'],
  ['accent-soft', 'iris-3', 'iris-3'],
  ['accent-soft-hover', 'iris-4', 'iris-4'],
  ['accent-line', 'iris-7', 'iris-7'],
  // shadcn / sandbox-ui HSL layer.
  ['hsl-background', W, 'mauve-1', 'hsl'],
  ['hsl-foreground', 'mauve-12', 'mauve-12', 'hsl'],
  ['hsl-card', W, 'mauve-2', 'hsl'],
  ['hsl-card-foreground', 'mauve-12', 'mauve-12', 'hsl'],
  ['hsl-popover', W, 'mauve-3', 'hsl'],
  ['hsl-popover-foreground', 'mauve-12', 'mauve-12', 'hsl'],
  ['hsl-primary', 'iris-9', 'iris-9', 'hsl'],
  ['hsl-primary-foreground', W, W, 'hsl'],
  ['hsl-secondary', 'mauve-3', 'mauve-3', 'hsl'],
  ['hsl-secondary-foreground', 'mauve-12', 'mauve-12', 'hsl'],
  ['hsl-muted', 'mauve-3', 'mauve-3', 'hsl'],
  ['hsl-muted-foreground', 'mauve-11', 'mauve-11', 'hsl'],
  ['hsl-accent', 'mauve-4', 'mauve-4', 'hsl'],
  ['hsl-accent-foreground', 'mauve-12', 'mauve-12', 'hsl'],
  ['hsl-destructive', 'red-11', 'red-4', 'hsl'],
  ['hsl-destructive-foreground', W, 'red-12', 'hsl'],
  ['hsl-border', 'mauve-6', 'mauve-6', 'hsl'],
  // `border-input` is the field outline in the ui Input, so it takes the field step.
  ['hsl-input', 'mauve-9', 'mauve-9', 'hsl'],
  ['hsl-ring', 'iris-9', 'iris-10', 'hsl'],
  ['hsl-success', 'green-9', 'green-9', 'hsl'],
  ['hsl-warning', 'amber-9', 'amber-9', 'hsl'],
  ['hsl-info', 'blue-9', 'blue-9', 'hsl'],
  ['sidebar-background', 'mauve-2', 'mauve-2', 'hsl'],
  ['sidebar-foreground', 'mauve-12', 'mauve-12', 'hsl'],
  ['sidebar-primary', 'iris-9', 'iris-9', 'hsl'],
  ['sidebar-primary-foreground', W, W, 'hsl'],
  ['sidebar-accent', 'mauve-4', 'mauve-4', 'hsl'],
  ['sidebar-accent-foreground', 'mauve-12', 'mauve-12', 'hsl'],
  ['sidebar-border', 'mauve-6', 'mauve-6', 'hsl'],
  ['sidebar-ring', 'iris-9', 'iris-10', 'hsl'],
  // MD3 family.
  ['md3-surface', W, 'mauve-1'],
  ['md3-surface-dim', 'mauve-2', 'mauve-1'],
  ['md3-surface-bright', W, 'mauve-5'],
  ['md3-surface-container-lowest', W, 'mauve-1'],
  ['md3-surface-container-low', 'mauve-2', 'mauve-2'],
  ['md3-surface-container', W, 'mauve-2'],
  ['md3-surface-container-high', 'mauve-3', 'mauve-3'],
  ['md3-surface-container-highest', W, 'mauve-4'],
  ['md3-surface-variant', 'mauve-3', 'mauve-3'],
  ['md3-on-surface', 'mauve-12', 'mauve-12'],
  ['md3-on-surface-variant', 'mauve-11', 'mauve-11'],
  ['md3-primary', 'iris-11', 'iris-11'],
  ['md3-primary-dim', 'iris-10', 'iris-10'],
  ['md3-primary-container', 'iris-9', 'iris-9'],
  ['md3-on-primary', W, W],
  ['md3-on-primary-container', W, W],
  ['md3-outline', 'mauve-9', 'mauve-9'],
  ['md3-outline-variant', 'mauve-6', 'mauve-6'],
  ['md3-error', 'red-11', 'red-11'],
  ['md3-error-container', 'red-3', 'red-3'],
  ['md3-on-error-container', 'red-12', 'red-12'],
  // Depth, bg, text and border families.
  ['depth-1', W, 'mauve-1'],
  ['depth-2', W, 'mauve-2'],
  ['depth-3', 'mauve-2', 'mauve-3'],
  ['depth-4', W, 'mauve-4'],
  ['bg-root', W, 'mauve-1'],
  ['bg-dark', 'mauve-2', 'mauve-1'],
  ['bg-elevated', W, 'mauve-3'],
  ['bg-section', 'mauve-2', 'mauve-1'],
  ['bg-input', W, 'mauve-2'],
  ['bg-hover', 'mauve-3', 'mauve-3'],
  ['bg-selection', 'iris-4', 'iris-5'],
  ['text-primary', 'mauve-12', 'mauve-12'],
  ['text-secondary', 'mauve-12', 'mauve-12'],
  ['text-muted', 'mauve-11', 'mauve-11'],
  ['text-dim', 'mauve-11', 'mauve-11'],
  ['border-subtle', 'mauve-6', 'mauve-6'],
  ['border-default', 'mauve-7', 'mauve-7'],
  ['border-hover', 'mauve-8', 'mauve-8'],
  ['border-accent', 'iris-7', 'iris-7'],
  ['border-accent-hover', 'iris-8', 'iris-8'],
  ['btn-primary-bg', 'iris-9', 'iris-9'],
  ['btn-primary-hover', 'iris-10', 'iris-10'],
  ['btn-primary-text', W, W],
  ['btn-cta-bg', 'iris-9', 'iris-9'],
  ['btn-cta-text', W, W],
  ['accent-surface-soft', 'iris-2', 'iris-2'],
  ['accent-surface-strong', 'iris-4', 'iris-4'],
  // Status chip: step 3 fill, step 6 border. Its text is step 12 in light,
  // because step 11 on step 3 measures 4.21-4.25:1 there, and step 11 in dark.
  // The categorical violet / orange / teal chips are the tone family below,
  // written into tokens.css; this layer does not redefine them.
  ...['success:green', 'warning:amber', 'danger:red', 'info:blue'].flatMap(
    (p) => {
      const [n, r] = p.split(':')
      return [
        [`surface-${n}-bg`, `${r}-3`, `${r}-3`],
        [`surface-${n}-border`, `${r}-6`, `${r}-6`],
        [`surface-${n}-text`, `${r}-12`, `${r}-11`],
      ]
    },
  ),
  ['surface-neutral-bg', 'mauve-3', 'mauve-3'],
  ['surface-neutral-border', 'mauve-6', 'mauve-6'],
  ['surface-neutral-text', 'mauve-11', 'mauve-11'],
  // Status text set straight on the page: step 11 passes 4.5:1 on white and on dark steps 1-2.
  ['status-running', 'green-11', 'green-11'],
  ['status-creating', 'iris-11', 'iris-11'],
  ['status-stopped', 'amber-11', 'amber-11'],
  ['status-warm', 'orange-11', 'orange-11'],
  ['status-cold', 'blue-11', 'blue-11'],
  ['status-error', 'red-11', 'red-11'],
  ['status-deleted', 'mauve-11', 'mauve-11'],
  ['brand-primary', 'iris-9', 'iris-9'],
  ['brand-strong', 'iris-12', 'iris-3'],
  ['brand-vibrant', 'iris-9', 'iris-9'],
]

const emit = (theme) =>
  MAP.map(([t, l, d, kind]) => {
    const ref = theme === 'light' ? l : d
    if (kind === 'hsl') return `  --${t}: ${hsl(hex(ref, theme))};`
    return `  --${t}: ${ref.startsWith('#') ? ref : `var(--${ref})`};`
  }).join('\n')

// Type roles use Tailwind's --text-<role> naming, so a `text-<role>` utility
// carries size, leading, tracking and weight together.
const TYPE = [
  ['display', 'clamp(2.5rem, 2rem + 3vw, 4rem)', '1.02', '-0.035em', '650'],
  ['hero', 'clamp(2.25rem, 2.2rem + 1.6vw, 3.5rem)', '1.05', '-0.03em', '650'],
  ['title', '2rem', '2.25rem', '-0.03em', '600'],
  ['page', '1.625rem', '1.875rem', '-0.02em', '600'],
  ['section', '1.375rem', '1.625rem', '-0.02em', '600'],
  ['lead', '1.125rem', '1.5rem', '0em', '600'],
  ['chat', '0.9375rem', '1.375rem', '0em', '400'],
  ['figure', '2.75rem', '2.75rem', '-0.02em', '600'],
]
const typeVars = TYPE.map(
  ([n, size, lh, tr, w]) =>
    `  --text-${n}: ${size};\n  --text-${n}--line-height: ${lh};\n  --text-${n}--letter-spacing: ${tr};\n  --text-${n}--font-weight: ${w};`,
).join('\n')

const shared = `
  /* The brand call to action. Use it once per page, on the primary consumer
   * action. White text passes on every stop (5.37, 5.39 and 5.18:1). */
  --cta: linear-gradient(90deg, #5b5bd6 0%, #6e56cf 55%, #8e4ec6 100%);
  --cta-hover: linear-gradient(90deg, #5151cd 0%, #654dc4 55%, #8347b9 100%);
  /* Radius by role. The numeric --radius-sm..xl scale is unchanged, so no
   * existing surface re-rounds; new surfaces pick the role they play. */
  --radius-tag: 4px;
  --radius-chip: 8px;
  --radius-field: 12px;
  --radius-panel: 16px;
  --radius-cover: 20px;
  --radius-sheet: 24px;
  --radius-pill: 999px;
  /* Motion. */
  --ease-standard: cubic-bezier(0.2, 0, 0, 1);
  --ease-emphasized: cubic-bezier(0.32, 0.72, 0, 1);
  --dur-press: 120ms;
  --dur-hover: 200ms;
  --dur-card: 250ms;
  --dur-sheet: 320ms;
  --dur-reveal: 450ms;
  /* Type. 12 px is the floor. */
  --font-size-xs: 0.75rem;
${typeVars}`

const shadowsLight = `
  /* Elevation. In light, shadow separates a card from the white page. */
  --shadow-1: 0 0 0 1px rgb(33 31 38 / 0.03), 0 2px 6px rgb(33 31 38 / 0.05), 0 4px 8px rgb(33 31 38 / 0.08);
  --shadow-2: 0 0 0 1px rgb(33 31 38 / 0.04), 0 6px 16px rgb(33 31 38 / 0.12);
  --shadow-3: 0 8px 28px rgb(33 31 38 / 0.28);
  --shadow-card: var(--shadow-1);
  --shadow-dropdown: var(--shadow-2);
  --shadow-overlay: var(--shadow-3);`
const shadowsDark = `
  /* Elevation. In dark, a white hairline states the edge; only floating layers cast a shadow. */
  --shadow-1: inset 0 0 0 1px rgb(255 255 255 / 0.06);
  --shadow-2: inset 0 0 0 1px rgb(255 255 255 / 0.08), 0 8px 24px rgb(0 0 0 / 0.5);
  --shadow-3: inset 0 0 0 1px rgb(255 255 255 / 0.1), 0 16px 48px rgb(0 0 0 / 0.6);
  --shadow-card: var(--shadow-1);
  --shadow-dropdown: var(--shadow-2);
  --shadow-overlay: var(--shadow-3);`

const system = `/* Semantic layer. Generated by scripts/gen-ladders.mjs; edit the MAP there, not this file.
 *
 * Requires ladders.css. Every token family (hsl, md3, depth, bg, text, border,
 * surface, status, btn) points at a ladder step, so components built on these
 * tokens re-skin without edits. Light pages are white and cards separate from
 * them by shadow and media. Dark steps surfaces up in small lightness
 * increments, draws hairline edges, and casts a shadow only under floating
 * layers. Chrome is neutral (mauve); colour belongs to content and to one
 * call to action per page. */
${DARK_SEL} {
${emit('dark')}${shared}${shadowsDark}
  color-scheme: dark;
}
${LIGHT_SEL} {
${emit('light')}${shared}${shadowsLight}
  color-scheme: light;
}
@media (prefers-reduced-motion: reduce) {
${`${DARK_SEL},\n${LIGHT_SEL}`.replace(/^/gm, '  ')} {
    --dur-press: 0ms;
    --dur-hover: 0ms;
    --dur-card: 0ms;
    --dur-sheet: 0ms;
    --dur-reveal: 0ms;
  }
}
`

// ── tones (tokens.css) ─────────────────────────────────────────────────────
// Categorical tones tell kinds of things apart: entities, file types,
// capabilities. They never report a state; status keeps its own hand-tuned
// --surface-{success,warning,danger,info,neutral}-* triples above.
//
// The set was chosen by measurement, not taste: of the Radix ramps, these eight
// keep the widest minimum OKLab distance between every pair on the icon and
// text steps in both themes, and none sits within
// 8 of the iris brand accent. Radix violet is 3.1 from iris, so the `violet`
// category reads from the purple ramp; the name is kept because
// --surface-violet-* already ships. Append new categories; reordering or
// renaming one changes what an existing tile means.
const CATEGORY = {
  violet: 'purple',
  orange: 'orange',
  teal: 'teal',
  blue: 'blue',
  pink: 'pink',
  brown: 'brown',
  cyan: 'cyan',
  lime: 'lime',
}
// The pre-existing categorical names, kept as aliases of the family.
const LEGACY_SURFACE = ['violet', 'orange', 'teal']

const lin = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
const channels = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16) / 255)
const lum = (h) => {
  const [r, g, b] = channels(h).map(lin)
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}
const contrast = (a, b) => {
  const [hi, lo] = [lum(a), lum(b)].sort((x, y) => y - x)
  return (hi + 0.05) / (lo + 0.05)
}
const oklab = (h) => {
  const [r, g, b] = channels(h).map(lin)
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675778 * s,
  ]
}
const distance = (a, b) => {
  const [p, q] = [oklab(a), oklab(b)]
  return Math.hypot(p[0] - q[0], p[1] - q[1], p[2] - q[2]) * 100
}

// The tones sit on the canonical planes in tokens.css, not on the Radix
// backgrounds, so they are solved against the resting card read from there.
const TOKENS_FILE = path.join(OUT, 'tokens.css')
const tokensSource = fs.readFileSync(TOKENS_FILE, 'utf8')
const cardIn = (nth) => {
  const all = [...tokensSource.matchAll(/--md3-surface-container:\s*(#[0-9a-fA-F]{6})/g)].map((m) => m[1].toLowerCase())
  if (all.length !== 2) throw new Error(`tokens.css: expected exactly 2 --md3-surface-container hex values (dark, light), found ${all.length}`)
  return all[nth]
}
const CARD = { dark: cardIn(0), light: cardIn(1) }

// One value per role, solved per ramp and theme. Every rule is a floor the
// generator enforces; an unsatisfiable ramp fails the build instead of shipping.
//
// Light sits on white paper, so it reads Radix steps directly:
//   bg 3 (a wash at most 1.25:1 from paper; the border separates the chip),
//   hover 4, selected 5, border 6.
// Dark cannot: Radix's dark step 3 sits BELOW the #303030 card, and a sunken
// chip reads as coloured text, while the next steps jump too far to leave room
// for a hover and a selected fill under step-12 text. So dark fills are the
// ramp's step 9 mixed into the card, at the least amount that lifts the fill
// 1.3:1 (bg), 1.45:1 (hover) and 1.6:1 (selected) off it — the same low-chroma
// raised tint as the hand-tuned status chips. Border is dark step 8.
// Both themes:
//   text             step 12, at least 4.5:1 on bg, hover and selected.
//   icon             the first of steps 9-12 with 3:1 on all three fills.
//   border-selected  the icon value: a non-text edge at 3:1. Selection also
//                    shows a check, so it never rests on colour alone.
const hexOf = (rgb) => `#${rgb.map((c) => Math.round(c * 255).toString(16).padStart(2, '0')).join('')}`
const mix = (a, b, t) => hexOf(channels(a).map((c, i) => c * t + channels(b)[i] * (1 - t)))
const lift = (tint, card, target) => {
  for (let t = 0.01; t <= 1; t += 0.01) {
    const fill = mix(tint, card, t)
    if (lum(fill) > lum(card) && contrast(fill, card) >= target) return fill
  }
  throw new Error(`${tint} cannot lift ${target}:1 off ${card}`)
}
const solve = (name, ramp, theme) => {
  const at = (step) => R[ramp][theme][step - 1]
  const card = CARD[theme]
  const fills =
    theme === 'light'
      ? [at(3), at(4), at(5)]
      : [1.3, 1.45, 1.6].map((target) => lift(at(9), card, target))
  if (theme === 'light' && contrast(fills[0], card) > 1.25) {
    throw new Error(`${name} light: step 3 is no longer a wash on the card`)
  }
  const text = at(12)
  const failing = fills.find((f) => contrast(text, f) < 4.5)
  if (failing) throw new Error(`${name} ${theme}: text ${text} under 4.5:1 on ${failing}`)
  const iconStep = [9, 10, 11, 12].find((s) => fills.every((f) => contrast(at(s), f) >= 3))
  if (!iconStep) throw new Error(`${name} ${theme}: no icon step clears 3:1`)
  return {
    bg: fills[0],
    'bg-hover': fills[1],
    'bg-selected': fills[2],
    border: theme === 'light' ? at(6) : at(8),
    'border-selected': at(iconStep),
    text,
    icon: at(iconStep),
  }
}

const TONES = Object.fromEntries(
  ['dark', 'light'].map((theme) => [
    theme,
    Object.fromEntries(Object.entries(CATEGORY).map(([name, ramp]) => [name, solve(name, ramp, theme)])),
  ]),
)

// Distinctness is the reason the set exists: hold it on the icon step, the
// mark that carries the category (8.1 dark, 7.1 light today; teal/cyan is the
// closest pair), so a new category that collides with an old one fails here.
// Text is step 12, ink tinted toward the hue, and light fills are near-white
// washes; neither is meant to tell categories apart on its own.
for (const theme of ['dark', 'light']) {
  const names = Object.keys(CATEGORY)
  for (let i = 0; i < names.length; i++) {
    for (let j = i + 1; j < names.length; j++) {
      const d = distance(TONES[theme][names[i]].icon, TONES[theme][names[j]].icon)
      if (d < 5.5) throw new Error(`${theme} icon: ${names[i]} and ${names[j]} are ${d.toFixed(1)} apart in OKLab (floor 5.5)`)
    }
  }
}

const toneRegion = (theme) => {
  const lines = ['  /* tones:begin — generated by scripts/gen-ladders.mjs; edit its CATEGORY map, not these lines. */']
  for (const [name, roles] of Object.entries(TONES[theme])) {
    for (const [role, value] of Object.entries(roles)) lines.push(`  --tone-${name}-${role}: ${value};`)
  }
  // Literal values rather than var() aliases: tests and consumers read these
  // as hex, and this generator is the only writer of both. The legacy -text
  // names keep their hue: sandbox-ui colours glyphs with them straight on the
  // card, so they take step 11, darkened toward step 12 only as far as 4.5:1
  // on the fill needs (light orange and teal).
  for (const name of LEGACY_SURFACE) {
    const tone = TONES[theme][name]
    const ramp = R[CATEGORY[name]][theme]
    let text = ramp[10]
    for (let t = 0.01; contrast(text, tone.bg) < 4.5; t += 0.01) text = mix(ramp[11], ramp[10], t)
    lines.push(`  --surface-${name}-bg: ${tone.bg};`, `  --surface-${name}-border: ${tone.border};`, `  --surface-${name}-text: ${text};`)
  }
  lines.push('  /* tones:end */')
  return lines.join('\n')
}
const REGION = /^ {2}\/\* tones:begin[^\n]*\*\/\n(?:.*\n)*? {2}\/\* tones:end \*\//gm
const regions = tokensSource.match(REGION) ?? []
if (regions.length !== 2) throw new Error(`tokens.css: expected 2 tone regions (dark, light), found ${regions.length}`)
let regionIndex = 0
const tokens = tokensSource.replace(REGION, () => toneRegion(regionIndex++ === 0 ? 'dark' : 'light'))

// ── tone scopes (tokens.css) ───────────────────────────────────────────────
// data-tone="<category>" on an element exposes that family under one set of
// names, so a stylesheet can paint a cover, tile or avatar with whichever
// category its data names: `background: var(--tone-bg)`. The family values
// already follow the theme, so these aliases need no light/dark copy.
const TONE_ROLES = Object.keys(TONES.dark[Object.keys(CATEGORY)[0]])
const toneScopes = [
  '/* tone-scopes:begin — generated by scripts/gen-ladders.mjs; edit its CATEGORY map, not these lines. */',
  ...Object.keys(CATEGORY).map(
    (name) => `[data-tone="${name}"] {\n${TONE_ROLES.map((role) => `  --tone-${role}: var(--tone-${name}-${role});`).join('\n')}\n}`,
  ),
  '/* tone-scopes:end */',
].join('\n')
const SCOPES = /\/\* tone-scopes:begin[^\n]*\*\/\n(?:.*\n)*?\/\* tone-scopes:end \*\//m
if (!SCOPES.test(tokens)) throw new Error('tokens.css: the tone-scopes region is missing')
const tokensOut = tokens.replace(SCOPES, toneScopes)

// ── agents named theme (named-themes.css) ──────────────────────────────────
// Agent Builder's identity: white light pages whose cards separate by shadow,
// and a mauve neutral ladder in both modes. It is the MAP above restricted to
// the canonical spine: surfaces, text and borders only. Accent, status and
// category tokens keep their canonical values, so the theme can never change
// what the brand colour, a state or a category looks like. Values are literal,
// so the theme needs no ladders.css.
const KEEP_CANONICAL =
  /^(hsl-(primary|ring|destructive|success|warning|info)|sidebar-(primary|ring)|md3-(primary|on-primary|error|on-error|surface-tint)|bg-selection|border-accent|btn-|accent-|brand-|surface-|status-)/
const NAMED_FILE = path.join(OUT, 'named-themes.css')
const namedSource = fs.readFileSync(NAMED_FILE, 'utf8')
// A named theme overrides spine tokens and never introduces a name, so the
// system.css-only roles (bg-page, line, fg, ink, accent-solid ...) stay out.
const inSpine = (t) => new RegExp(`--${t}:`).test(tokensSource)
const agentsMap = MAP.filter(([t]) => inSpine(t) && !KEEP_CANONICAL.test(t))
const agentsBlock = (theme) => {
  const decls = agentsMap.map(([t, l, d, kind]) => {
    const value = hex(theme === 'light' ? l : d, theme)
    return `  --${t}: ${kind === 'hsl' ? hsl(value) : value};`
  })
  const shadows = theme === 'light' ? shadowsLight : shadowsDark
  // shadow-1..3 are this generator's names; the spine reads the three roles.
  const [one, two, three] = [1, 2, 3].map((n) => shadows.match(new RegExp(`--shadow-${n}: ([^;]+);`))[1])
  decls.push(`  --shadow-card: ${one};`, `  --shadow-dropdown: ${two};`, `  --shadow-overlay: ${three};`)
  return decls.join('\n')
}
const agentsRegion = `/* agents:begin — generated by scripts/gen-ladders.mjs from its MAP; edit there, not these lines.
 * Agents (Agent Builder): white light pages, cards separated by shadow, and a
 * mauve neutral ladder. Surfaces, text and borders only; the accent, status
 * and category tokens stay canonical. Select data-theme="agents" for dark and
 * data-theme="agents-light" for light. */
[data-theme="agents"] {
${agentsBlock('dark')}
}
[data-theme="agents-light"] {
${agentsBlock('light')}
}
/* agents:end */`
const AGENTS = /\/\* agents:begin[^\n]*\n(?:.*\n)*?\/\* agents:end \*\//m
if (!AGENTS.test(namedSource)) throw new Error('named-themes.css: the agents region is missing')
const named = namedSource.replace(AGENTS, agentsRegion)

const outputs = [
  ['ladders.css', ladders],
  ['system.css', system],
  ['tokens.css', tokensOut],
  ['named-themes.css', named],
]
if (CHECK) {
  const stale = outputs.filter(([file, text]) => fs.readFileSync(path.join(OUT, file), 'utf8') !== text).map(([f]) => f)
  if (stale.length) {
    console.error(`stale: ${stale.join(', ')}; run pnpm --filter @tangle-network/brand gen:ladders`)
    process.exit(1)
  }
  console.log('ladders.css, system.css, the tokens.css tone regions and the agents theme are current.')
} else {
  fs.mkdirSync(OUT, { recursive: true })
  for (const [file, text] of outputs) fs.writeFileSync(path.join(OUT, file), text)
  console.log(`wrote ladders.css, system.css (${MAP.length} tokens per theme), ${Object.keys(CATEGORY).length} tones and their data-tone scopes in tokens.css, and the agents theme in named-themes.css to ${OUT}`)
}
