#!/usr/bin/env node
// Generates src/palette.generated.ts: Brand's resolved colors for renderers that
// cannot read CSS variables (PDF, canvas, WebGL, email, the theme-color meta).
// Values are read from tokens.css and named-themes.css; run with --check in build.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const here = path.dirname(new URL(import.meta.url).pathname);
const styles = path.join(here, "..", "src", "styles");
const OUT = path.join(here, "..", "src", "palette.generated.ts");
const tokens = readFileSync(path.join(styles, "tokens.css"), "utf8");
const named = readFileSync(path.join(styles, "named-themes.css"), "utf8");

// The body of the first rule whose selector list ends with `last` (the selector the brace follows).
function block(css, last) {
  const re = new RegExp(`${last.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*\\{`, "g");
  const m = re.exec(css);
  if (!m) throw new Error(`no block for ${last}`);
  let depth = 1, i = m.index + m[0].length;
  const start = i;
  for (; i < css.length && depth; i++) depth += css[i] === "{" ? 1 : css[i] === "}" ? -1 : 0;
  return css.slice(start, i - 1);
}
const decls = (body) => {
  const out = {};
  for (const m of body.replace(/\/\*[\s\S]*?\*\//g, "").matchAll(/--([a-z0-9-]+)\s*:\s*([^;]+);/g)) out[m[1]] = m[2].trim();
  return out;
};
const DARK = decls(block(tokens, ".dark"));
const LIGHT = { ...DARK, ...decls(block(tokens, "\n.light")) };
const WEBSITE_LIGHT = { ...LIGHT, ...decls(block(named, '[data-theme="website"]:where(:not(.dark))')) };
const WEBSITE_DARK = { ...DARK, ...decls(block(named, '.dark[data-theme="website"]')) };

const hslHex = (h, s, l) => {
  s /= 100; l /= 100;
  const f = (n) => { const k = (n + h / 30) % 12; const a = s * Math.min(l, 1 - l); return l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1)); };
  return "#" + [f(0), f(8), f(4)].map((x) => Math.round(x * 255).toString(16).padStart(2, "0")).join("");
};
function resolve(scope, name, seen = new Set()) {
  if (seen.has(name)) throw new Error(`cycle at --${name}`);
  seen.add(name);
  let v = scope[name];
  if (v == null) throw new Error(`--${name} is not defined`);
  const ref = v.match(/^var\(--([a-z0-9-]+)\)$/);
  if (ref) return resolve(scope, ref[1], seen);
  const hsl = v.match(/^hsl\(var\(--([a-z0-9-]+)\)\)$/);
  if (hsl) v = resolve(scope, hsl[1], seen);
  const tri = v.match(/^([\d.]+)\s+([\d.]+)%\s+([\d.]+)%$/);
  if (tri) return hslHex(+tri[1], +tri[2], +tri[3]);
  if (/^#[0-9a-fA-F]{6}$/.test(v)) return v.toLowerCase();
  if (/^#[0-9a-fA-F]{3}$/.test(v)) return ("#" + [...v.slice(1)].map((c) => c + c).join("")).toLowerCase();
  if (/^rgba?\(/.test(v)) return v;
  throw new Error(`--${name}: cannot resolve "${v}"`);
}
// Role name -> token. Planes, ink, accent, status surfaces and the indigo ramp.
const ROLES = {
  canvas: "md3-surface", card: "md3-surface-container", well: "md3-surface-container-low",
  nested: "md3-surface-container-high", overlay: "md3-surface-container-highest", deepest: "md3-surface-container-lowest",
  hairline: "md3-outline-variant", ink: "text-primary", inkSecondary: "text-secondary", inkMuted: "text-muted",
  accent: "btn-primary-bg", accentHover: "btn-primary-hover", onAccent: "btn-primary-text", accentText: "accent-text",
  danger: "hsl-destructive",
  successBg: "surface-success-bg", successBorder: "surface-success-border", successText: "surface-success-text",
  warningBg: "surface-warning-bg", warningBorder: "surface-warning-border", warningText: "surface-warning-text",
  dangerBg: "surface-danger-bg", dangerBorder: "surface-danger-border", dangerText: "surface-danger-text",
  infoBg: "surface-info-bg", infoBorder: "surface-info-border", infoText: "surface-info-text",
  brandVibrant: "brand-vibrant", brandCool: "brand-cool", brandGlow: "brand-glow", brandPurple: "brand-purple",
};
const palette = (scope) => Object.fromEntries(Object.entries(ROLES).map(([k, t]) => [k, resolve(scope, t)]));
const lit = (o) => "{\n" + Object.entries(o).map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`).join("\n") + "\n  }";
const src = `// GENERATED by scripts/gen-palette.mjs from tokens.css and named-themes.css; do not edit.
// Brand's resolved colors for renderers that cannot read CSS variables: PDF, canvas,
// WebGL, email and the theme-color meta. Pages styled with CSS use the variables.

/** A theme's resolved roles: hex strings, or rgba() where the token is translucent. */
export interface BrandPalette {
${Object.keys(ROLES).map((k) => `  ${k}: string;`).join("\n")}
}

/** Resolved palettes for the canonical light and dark themes and the website named theme. */
export const palettes = {
  light: ${lit(palette(LIGHT))},
  dark: ${lit(palette(DARK))},
  websiteLight: ${lit(palette(WEBSITE_LIGHT))},
  websiteDark: ${lit(palette(WEBSITE_DARK))},
} as const satisfies Record<string, BrandPalette>;
`;
if (process.argv.includes("--check")) {
  if (readFileSync(OUT, "utf8") !== src) { console.error("src/palette.generated.ts is stale: run node scripts/gen-palette.mjs"); process.exit(1); }
} else { writeFileSync(OUT, src); console.log("wrote src/palette.generated.ts"); }
